# WirelessTelemetry message
# ---

float32 rx_bytes_mb
float32 tx_bytes_mb

float32 rx_bytes_kb
float32 tx_bytes_kb

uint32 rx_packets
uint32 tx_packets

uint32 rx_drop
uint32 tx_drop

uint32 rx_error
uint32 tx_error

uint32 link_downs

float32 rx_mbps
float32 tx_mbps

float32 rx_kbps
float32 tx_kbps

float32 rx_packets_per_sec
float32 tx_packets_per_sec

float32 rx_drops_per_sec
float32 tx_drops_per_sec

float32 rx_errors_per_sec
float32 tx_errors_per_sec

int32 signal_strength
int32 signal_to_noise

float32 tx_rate
float32 rx_rate

uint32 tx_ccq
uint32 rx_ccq